# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d966b1e2522ec7cae7492145b3e4740c5eed5c0ee33551b8e2de268f0267daba89fab0a32219844656869886c777ad9271009e82c7f9e0275b08d176db598f1

test:
  secret_key_base: 2d9fb91b5739ffd4cd9943158984bbe6c3404cf5e3d3c5678386495c5466308e83fc1592aecb2a06bb4f7dceae40824848f4559a8ffa7c11aa40fa205baff057

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
